import type { NextPage } from "next";
import React from "react";
import Head from "next/head";
import Image from "next/image";
import Divider from "win-ui/divider";
import Flyout from "win-ui/flyout";
import List from "win-ui/list";
import MenuList from "win-ui/menu-list";
import MenuItem from "win-ui/menu-item";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const list = React.useRef(null);
  const [selectedIndex, setSelectedIndex] = React.useState(1);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div
          style={{
            display: "flex",
            justifyContent: "space-around",
            width: "100%",
          }}
        >
          <MenuList ref={list}>
            <MenuItem
              variant="standard"
              selected={selectedIndex === 0}
              // indented
              // startIcon={<span className="WinUI-icon CircleRing" />}
              // hintText="Hint"
              onClick={() => setSelectedIndex(0)}
            >
              Text
            </MenuItem>
            <MenuItem
              selected={selectedIndex === 1}
              onClick={() => setSelectedIndex(1)}
            >
              Text
            </MenuItem>
            <MenuItem
              selected={selectedIndex === 2}
              onClick={() => setSelectedIndex(2)}
            >
              Text
            </MenuItem>
            <MenuItem
              selected={selectedIndex === 3}
              onClick={() => setSelectedIndex(3)}
            >
              Text
            </MenuItem>
            <MenuItem
              selected={selectedIndex === 4}
              onClick={() => setSelectedIndex(4)}
            >
              Text
            </MenuItem>
            <MenuItem
              selected={selectedIndex === 5}
              onClick={() => setSelectedIndex(5)}
            >
              Text
            </MenuItem>
          </MenuList>
        </div>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
